### ISSUE TITLE
Cannot run game

### ISSUE THREAD

**Issue by stanek** [j-masci/game-1#1]
`Rafal@LAPTOP-CTHE5R0J MINGW64 ~/Desktop/game-1-master
$ python start.py
start.py:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if E.code is "restart":
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "start.py", line 2, in <module>
    import game
  File "C:\Users\Rafal\Desktop\game-1-master\game.py", line 3, in <module>
    from esper import esper
ImportError: cannot import name 'esper' from 'esper' (C:\Users\Rafal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\esper.py)

Rafal@LAPTOP-CTHE5R0J MINGW64 ~/Desktop/game-1-master
$ python --version
Python 3.8.1`

have tried pip install esper aswell to no avail

**Comment by j-masci** [comment]
Hmm yes I see. Esper I just copied and pasted into it. Its not in the git
ignore, but, it is its own git repo. Maybe mkdir esper. and then clone it.
https://github.com/benmoran56/esper Basically, just pujt that repo inside
of /esper and you should be good. Let me know if it works heh.

**Comment by j-masci** [comment]
Ok for now I just updated it to include esper when you clone. Not normally the way to include a package, but, i'm just screwing around and this works now.
